// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCX4IJNRNtRat86F0zDXqBb_JZMtqU1UXs',
    appId: '1:979062541753:web:73c4d44f6741aa5f0cba68',
    messagingSenderId: '979062541753',
    projectId: 'push-notifications-3ef4d',
    authDomain: 'push-notifications-3ef4d.firebaseapp.com',
    storageBucket: 'push-notifications-3ef4d.appspot.com',
    measurementId: 'G-F72XDL9ZXL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArdhE0NFFUpWO5VpTkUlsAF8Addovz_Kc',
    appId: '1:979062541753:android:bad36251e4f572080cba68',
    messagingSenderId: '979062541753',
    projectId: 'push-notifications-3ef4d',
    storageBucket: 'push-notifications-3ef4d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKNq8WkzcbHMTlfmRgZt_ZgNNIWs6oZSk',
    appId: '1:979062541753:ios:e05e4bd932f2b97b0cba68',
    messagingSenderId: '979062541753',
    projectId: 'push-notifications-3ef4d',
    storageBucket: 'push-notifications-3ef4d.appspot.com',
    iosBundleId: 'com.example.project1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKNq8WkzcbHMTlfmRgZt_ZgNNIWs6oZSk',
    appId: '1:979062541753:ios:f5623babcaaa41a30cba68',
    messagingSenderId: '979062541753',
    projectId: 'push-notifications-3ef4d',
    storageBucket: 'push-notifications-3ef4d.appspot.com',
    iosBundleId: 'com.example.project1.RunnerTests',
  );
}
